-- Phase 4 slices 4c-4e: creating a club, invites, and lifecycle.
--
-- Adds what a club needs in order to be created by somebody other than a SQL
-- prompt, joined by somebody who wasn't inserted by hand, and left or deleted
-- without orphaning anything.
--
-- Writes still go exclusively through edge functions with the service role, so
-- none of these tables gain an insert/update/delete policy. The one new READ
-- policy is for invites, because a librarian has to be able to see and revoke
-- their own club's codes -- and it's scoped by is_librarian() rather than
-- is_member(), since an invite code is a credential: any member being able to
-- list them would make "invite-only" meaningless.

-- 1. Clubs can generate their own ids -------------------------------------
-- `clubs.id` was created with no default: the one seeded row had its uuid
-- hardcoded, so nothing ever needed one. The plan's §2 sketch always had
-- `default gen_random_uuid()`; the real table just never got it, and creating a
-- club failed with a not-null violation on id.
alter table public.clubs alter column id set default gen_random_uuid();

-- 2. Club ownership -------------------------------------------------------
-- created_by is what per-user club-creation rate limiting counts, and who to
-- fall back to if a club somehow ends up with no librarian.
alter table public.clubs
  add column if not exists created_by uuid references auth.users(id) on delete set null;

create index if not exists clubs_created_by_idx on public.clubs (created_by, created_at desc);

-- Slug shape, enforced in the database as well as in create-club. The function
-- owns the friendly errors and the reserved-word list; this is the backstop that
-- keeps a bad slug out even if something writes directly with the service role.
-- Deliberately permits the two existing slugs.
alter table public.clubs drop constraint if exists clubs_slug_shape_chk;
alter table public.clubs
  add constraint clubs_slug_shape_chk
  check (slug ~ '^[a-z0-9](?:[a-z0-9-]{1,30}[a-z0-9])$' and slug !~ '--');

-- 3. is_librarian() -------------------------------------------------------
-- Sketched in the plan's §3 and deferred through Phase 2 because nothing needed
-- it: admin-update does its own application-level role query. The invite read
-- policy below is the first RLS *policy* that has to ask about a role.
create or replace function public.is_librarian(club uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.club_members
    where club_id = club and user_id = auth.uid() and role = 'librarian'
  );
$$;

-- 4. Invites --------------------------------------------------------------
-- `code` is the primary key and the credential: unguessable, generated by the
-- edge function. A row is spent when uses >= max_uses (when max_uses is set),
-- past expires_at, or explicitly revoked -- all three checked at join time
-- rather than by a constraint, so an exhausted invite stays visible in the
-- Admin tab as history instead of vanishing.
create table if not exists public.club_invites (
  code       text primary key,
  club_id    uuid not null references public.clubs(id) on delete cascade,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  expires_at timestamptz,
  max_uses   int check (max_uses is null or max_uses > 0),
  uses       int not null default 0,
  revoked    boolean not null default false
);

create index if not exists club_invites_club_idx on public.club_invites (club_id, created_at desc);

alter table public.club_invites enable row level security;

drop policy if exists "club_invites read for librarians" on public.club_invites;
create policy "club_invites read for librarians"
  on public.club_invites for select
  to authenticated
  using (is_librarian(club_id));

-- 5. Grants ---------------------------------------------------------------
-- Same reasoning as 20260809150000: RLS decides which rows, privileges decide
-- whether the role may touch the table at all.
grant all on table public.club_invites to anon, authenticated, service_role;

-- 6. Cascade deletes from clubs -------------------------------------------
-- Deleting a club has to be possible, and every club_id column was added as a
-- plain `references public.clubs(id)` with no ON DELETE action -- so a delete
-- failed with a 23503 against the first child table it hit. (The plan's §2 said
-- cascade deletes came "for free" with the `reads` table; they never did.)
--
-- Rewrites every foreign key pointing at clubs to ON DELETE CASCADE, discovering
-- them from the catalog rather than naming them, so a table added later that
-- forgets is picked up the next time this pattern is reused. Skips any that
-- already cascade, and the referencing column is `club_id` on all of them.
do $$
declare r record;
begin
  for r in
    select c.conname, c.conrelid::regclass::text as tbl
    from pg_constraint c
    where c.confrelid = 'public.clubs'::regclass
      and c.contype = 'f'
      and c.confdeltype <> 'c'
  loop
    execute format('alter table %s drop constraint %I', r.tbl, r.conname);
    execute format(
      'alter table %s add constraint %I foreign key (club_id) references public.clubs(id) on delete cascade',
      r.tbl, r.conname
    );
  end loop;
end $$;

-- 7. Backfill created_by --------------------------------------------------
-- The seeded club predates the column. Attribute it to its first librarian so
-- rate-limit counting and the "who owns this" question have an answer.
update public.clubs c
set created_by = (
  select cm.user_id from public.club_members cm
  where cm.club_id = c.id and cm.role = 'librarian'
  order by cm.joined_at limit 1
)
where c.created_by is null;
